spring:
  #profiles: 
      #active: cloud
  jpa:
    show-sql: true
    properties:
      hibernate.dialect: "org.hibernate.dialect.MySQL55Dialect"
      hibernate.hbm2ddl.import_files: import.sql
    hibernate:
      ddl-auto: update
      
  datasource:
    url: "jdbc:mysql://10.200.30.37:3306/cf_089d7116_cbae_4e6e_a7bb_7f5e6168e965"
    username: "ZmMLRcf4jAjdUfKO"
    password: "jDtc1dQorohk0AAd"
    initialization-mode: always
        #cloud: 
      #config: 
        #uri: ${vcap.services.my_config_server_svc.credentials.url}    
info: # add this section
  build:
    artifact: @project.artifactId@
    name: @project.name@
    description: @project.description@
    version: @project.version@
management:
  endpoint:
    health:
      show-details: always
  security:
    enabled: false
  info:
    git:
      mode: full
  cloudfoundry:
    enabled: true
    skip-ssl-validation: false
  endpoints:
   web:
    exposure:
      include: "*"
        